services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ME_ADMIN_USERNAME}:${ME_ADMIN_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: ${ME_BASICAUTH}

  app:
    build: .
    restart: always
    environment:
      - MONGODB_URI=mongodb://${ME_ADMIN_USERNAME}:${ME_ADMIN_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
    volumes:
      - .:/app
volumes:
  mongo_data:
