spring: # be carefull during editing 
  config:
    import: optional:file:.env[.properties] # go to root of project 
  application:
    name: ${SPRING_APPLICATION_NAME:main} # optional no spring app name, take 'main' 
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:${DBMS}://${HOST}:${PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    platform: ${DB_PLATFORM}
    driver-class-name: ${DRIVE_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update 
      dialect: ${HIBERNATE_DIALECT}